### ISSUE TITLE
DNS resolution failed

### ISSUE THREAD

**Issue by ericchanky** [containous/maesh#475] opened 2020-03-26 06:36 UTC
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Change the address to `<service>.<namespace>.maesh:50051` with h2c enabled.
The first attempt to the service will give `DNS resolution failed`, the following attempts will also give this error randomly

### What did you expect to see?

The service can connect to `<service>.<namespace>.maesh:50051`

### What did you see instead?

DNS resolution failed

### Output of controller log: (_What version of Maesh are you using?_)

version: containous/maesh:v1.1.0
```
# no related log
```

### What is your environment & configuration (arguments, provider, platform, ...)?

provider: k8s 1.16 on aws
arguments:
```
args:
  - '--debug'
  - '--defaultMode=http'
  - '--namespace=$(POD_NAMESPACE)'
```

### If applicable, please paste the yaml objects required to reproduce your issue

maesh is Installed by helm v3

```
apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      k8s-app: lb-client
    name: lb-client
    namespace: test
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        k8s-app: lb-client
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          k8s-app: lb-client
        name: lb-client
      spec:
        containers:
        - command:
          - node
          - ./grpc-server/server.js
          image: pickupp/load-balancer-test:1.0.4
          imagePullPolicy: IfNotPresent
          name: lb-client
          resources: {}
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 10
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      k8s-app: lb-server
    name: lb-server
    namespace: test
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        k8s-app: lb-server
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          k8s-app: lb-server
        name: lb-server
      spec:
        containers:
        - env:
          - name: GRPC_SERVER
            value: lb-client.test.maesh:50051
          image: pickupp/load-balancer-test:1.0.4
          imagePullPolicy: IfNotPresent
          name: lb-server
          resources: {}
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 10
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      maesh.containo.us/scheme: h2c
    labels:
      k8s-app: lb-client
    name: lb-client
    namespace: test
  spec:
    ports:
    - name: tcp-50051-50051-6p2n4
      port: 50051
      protocol: TCP
      targetPort: 50051
    selector:
      k8s-app: lb-client
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      k8s-app: lb-server
    name: lb-server
    namespace: test
  spec:
    ports:
    - name: tcp-3000-3000-72sts
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      k8s-app: lb-server
    sessionAffinity: None
    type: ClusterIP
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

Step to reproduce:
1. scale down all services
2. scale up `lb-server` first and wait for it ready
3. scale up `lb-client`
4. access `lb-server` from browser
5. it shows DNS resolution failed in first attempt
6. reload to get normal response

**Comment by dtomcej** [comment] 2020-03-27 14:57
Hello @ericchanky,

Where is the error `DNS resolution failed` logged? In your app? In maesh? The browser?

Could you try with curl instead of the browser? Does the same issue present itself?

**Comment by ericchanky** [comment] 2020-03-28 10:38
Hi @dtomcej 

The error is logged in my app, the response is
```json
{"error":{"code":14,"metadata":{"_internal_repr":{},"flags":0},"details":"DNS resolution failed"}}
```

The related code is
```nodejs
const { echo } = grpc.loadPackageDefinition(proto)

const echoService = new echo.Echo(process.env.GRPC_SERVER || 'localhost:50051', grpc.credentials.createInsecure())

app.get('/', (req, res) => {
    echoService.getName({ message: req.query.name || '' }, (error, response) => {
        res.json({ error, response })
    })
})
```

**Comment by dtomcej** [comment] 2020-03-30 18:28
Hello @ericchanky,

When you scale up your services from 0 replicas, it may take a second or two for the Maesh endpoint to be available, as Maesh uses the kubernetes API to get service endpoints, with which to forward traffic to.

Can you provide some of the controller log to see if there is a delay in the creation of the config/services and or the config deploy to the proxy nodes?

**Comment by ericchanky** [comment] 2020-04-01 05:19
```
 Apr 01 12:58:35  maesh[maesh-controller-dd4746fc8-njwj7] time="2020-04-01T04:58:35Z" level=debug msg="Updated service: maesh/maesh-lb-server-6d61657368-test"
 Apr 01 12:58:35  maesh[maesh-controller-dd4746fc8-njwj7] time="2020-04-01T04:58:35Z" level=debug msg="MeshControllerHandler ObjectUpdated with type: *corev1.Service: test/lb-server"
 Apr 01 13:03:19  maesh[maesh-controller-dd4746fc8-njwj7] time="2020-04-01T05:03:19Z" level=debug msg="MeshControllerHandler ObjectUpdated with type: *corev1.Endpoints: test/lb-server"
 Apr 01 13:03:19  maesh[maesh-controller-dd4746fc8-njwj7] time="2020-04-01T05:03:19Z" level=debug msg="MeshControllerHandler ObjectUpdated with type: *corev1.Endpoints: test/lb-client"
 Apr 01 13:03:28  maesh[maesh-controller-dd4746fc8-njwj7] time="2020-04-01T05:03:28Z" level=debug msg="Updated service: maesh/maesh-lb-server-6d61657368-test"
 Apr 01 13:03:28  maesh[maesh-controller-dd4746fc8-njwj7] time="2020-04-01T05:03:28Z" level=debug msg="MeshControllerHandler ObjectUpdated with type: *corev1.Service: test/lb-server"
 Apr 01 13:03:36  maesh[maesh-controller-dd4746fc8-njwj7] time="2020-04-01T05:03:36Z" level=debug msg="Updated service: maesh/maesh-lb-client-6d61657368-test"
 Apr 01 13:03:36  maesh[maesh-controller-dd4746fc8-njwj7] time="2020-04-01T05:03:36Z" level=debug msg="MeshControllerHandler ObjectUpdated with type: *corev1.Service: test/lb-client"
 Apr 01 13:03:50  test[lb-server-74759bdc48-9jfzq] Example app listening on port 3000!
 Apr 01 13:03:50  maesh[maesh-controller-dd4746fc8-njwj7] time="2020-04-01T05:03:50Z" level=debug msg="MeshControllerHandler ObjectUpdated with type: *corev1.Endpoints: test/lb-server"
 Apr 01 13:04:10  test[lb-client-56f45d447-467x2] Service started at 0.0.0.0:50051
 Apr 01 13:04:11  maesh[maesh-controller-dd4746fc8-njwj7] time="2020-04-01T05:04:11Z" level=debug msg="MeshControllerHandler ObjectUpdated with type: *corev1.Endpoints: test/lb-client"
 Apr 01 13:04:17  test[lb-server-74759bdc48-9jfzq] request {}
 Apr 01 13:04:17  test[lb-server-74759bdc48-9jfzq] response {
 Apr 01 13:04:17  test[lb-server-74759bdc48-9jfzq]   error: Error: 14 UNAVAILABLE: DNS resolution failed
 Apr 01 13:04:17  test[lb-server-74759bdc48-9jfzq]       at Object.exports.createStatusError (/app/http-server/node_modules/grpc/src/common.js:91:15)
 Apr 01 13:04:17  test[lb-server-74759bdc48-9jfzq]       at Object.onReceiveStatus (/app/http-server/node_modules/grpc/src/client_interceptors.js:1209:28)
 Apr 01 13:04:17  test[lb-server-74759bdc48-9jfzq]       at InterceptingListener._callNext (/app/http-server/node_modules/grpc/src/client_interceptors.js:568:42)
 Apr 01 13:04:17  test[lb-server-74759bdc48-9jfzq]       at InterceptingListener.onReceiveStatus (/app/http-server/node_modules/grpc/src/client_interceptors.js:618:8)
 Apr 01 13:04:17  test[lb-server-74759bdc48-9jfzq]       at callback (/app/http-server/node_modules/grpc/src/client_interceptors.js:847:24) {
 Apr 01 13:04:17  test[lb-server-74759bdc48-9jfzq]     code: 14,
 Apr 01 13:04:17  test[lb-server-74759bdc48-9jfzq]     metadata: Metadata { _internal_repr: {}, flags: 0 },
 Apr 01 13:04:17  test[lb-server-74759bdc48-9jfzq]     details: 'DNS resolution failed'
 Apr 01 13:04:17  test[lb-server-74759bdc48-9jfzq]   },
 Apr 01 13:04:17  test[lb-server-74759bdc48-9jfzq]   response: undefined
 Apr 01 13:04:17  test[lb-server-74759bdc48-9jfzq] }
```

Maesh is quick enough to generate the service. It's more like GRPC issue that it cannot handle DNS resolution failed well. But I think it will be good to return `503` if there is no pods.

I also tested only bring up `lb-server`, it will show 503 correctly. Later on when I bring up `lb-client`, it will not show `DNS resultion failed` but connect correctly.

So it only occur when `lb-server` is up without `lb-client` and connect to `lb-client` when `lb-client` is up.

**Comment by ericchanky** [comment] 2020-04-08 16:44
Hello @dtomcej , any update for this?

**Comment by dtomcej** [comment] 2020-05-18 17:10
Hello @ericchanky,

We completely reworked how Maesh service creation was handled in v1.2,

Could you try installing Maesh v1.2 and see if this issue still persists?

Thanks!

**Comment by ericchanky** [comment] 2020-06-04 10:01
Hi @dtomcej 

Still no luck with v1.2, but somehow I can't reproduce it in docker desktop's k8s, do you think it is related to coredns or other k8s config?

**Comment by suerp** [comment] 2020-06-09 08:26
hello，using maesh-v1.2 in kubernetes-1.15 has some error:
control log -----time="2020-06-09T06:22:07Z" level=info msg="Configuration loaded from flags."
W0609 06:22:07.864021       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.

/ # curl server.maesh-test.maesh -v
* Expire in 0 ms for 6 (transfer 0x5555555b7620)
* Expire in 1 ms for 1 (transfer 0x5555555b7620)
* Expire in 0 ms for 1 (transfer 0x5555555b7620)
......
* Could not resolve host: server.maesh-test.maesh
* Expire in 5 ms for 1 (transfer 0x5555555b7620)
* Closing connection 0
curl: (6) Could not resolve host: server.maesh-test.maesh

**Comment by suerp** [comment] 2020-06-09 08:28
> hello，using maesh-v1.2 in kubernetes-1.15 has some error:
> control log -----time="2020-06-09T06:22:07Z" level=info msg="Configuration loaded from flags."
> W0609 06:22:07.864021 1 client_config.go:543] Neither --kubeconfig nor --master was specified. Using the inClusterConfig. This might not work.
> 
> / # curl server.maesh-test.maesh -v
> 
> * Expire in 0 ms for 6 (transfer 0x5555555b7620)
> * Expire in 1 ms for 1 (transfer 0x5555555b7620)
> * Expire in 0 ms for 1 (transfer 0x5555555b7620)
>   ......
> * Could not resolve host: server.maesh-test.maesh
> * Expire in 5 ms for 1 (transfer 0x5555555b7620)
> * Closing connection 0
>   curl: (6) Could not resolve host: server.maesh-test.maesh

@ericchanky @dtomcej

**Comment by kevinpollet** [comment] 2020-06-09 08:54
Hello @suerp,

If you need help, it's better to ask your question in the Maesh forum https://community.containo.us/c/maesh/15. GitHub issues are used to report bugs, ask for new features and not for support.

Btw, you'll have to give more context to your problem, what are you trying to do, deployed resources and what is your problem.

**Comment by suerp** [comment] 2020-06-10 02:41
> 你好@suerp，
> 
> 如果需要幫助，最好在Maesh論壇https://community.containo.us/c/maesh/15提問。GitHub問題用於報告錯誤並要求提供新功能，而不是尋求支持。
> 
> 順便說一句，您將不得不為問題提供更多的背景信息，您要做什麼，已部署的資源以及您的問題是什麼。

@kevinpollet 

> Hello @suerp,
> 
> If you need help, it's better to ask your question in the Maesh forum https://community.containo.us/c/maesh/15. GitHub issues are used to report bugs and ask for new features, not for support.
> 
> Btw, you'll have to give more context to your problem, what are you trying to do, deployed resources and what is your problem.

ok，thank you！

**Comment by suerp** [comment] 2020-06-10 02:42
> Hello @suerp,
> 
> If you need help, it's better to ask your question in the Maesh forum https://community.containo.us/c/maesh/15. GitHub issues are used to report bugs and ask for new features, not for support.
> 
> Btw, you'll have to give more context to your problem, what are you trying to do, deployed resources and what is your problem.

@kevinpollet  ok，thank you！

**Comment by jspdown** [comment] 2020-08-28 14:30
@ericchanky I tried to reproduce the bug you described on my local k3s cluster and on AWS. I couldn't reproduce it. 
At best here is the only error I got immediately after bringing back up the `lb-server` and `lb-client`:

```
{
  "error": {
    "code": 1,
    "metadata": {
      "_internal_repr": {},
      "flags": 0
    },
    "details": "Received http2 header with status: 503"
  },
 ...
}
```

This is a perfectly fine behavior as changes on the cluster can take few seconds to be taken into account. 503 is the expected response code.

As we cannot reproduce the bug on <=v1.2.x and 1.3.2, I'm going to close this issue.
If you are still experiencing issues of this sort and you found a way to reproduce it with great confidence, please feel free to open a new issue.

**Closed by jspdown** 2020-08-28 14:30 UTC
Labels: area/coredns, area/services, contributor/waiting-for-feedback, kind/bug/possible
